### ISSUE TITLE
Mines being forcefully exploded during level generation

### ISSUE THREAD

**Issue by jacksonp52** [Chrigi2486/CTModsLC#4]
Regular landmines are not intended to be blown up immediately, but the current state of the mod causes mines within the level to be forcefully triggered. I have written a quick hotfix for this and will be submitting a PR shortly.

**Comment by Chrigi2486** [comment]
Hey Jwaffled  
  
Thank you for your interest in the mod and your commitment to improving it!  
  
This was a known issue, that we thought we had fixed with the "kys" parameter, but I guess it's still an issue.
Currently as I understand your code it would also hinder new mines from being triggered after level generation, which would mean that the mod would lose its core functionality.  
  
We're currently working on a fix for this and we'll take your fix into consideration if our fix doesn't work.  
  
We appreciate your support for our mod!  
Regards  
Christian and Tom

**Comment by jacksonp52** [comment]
I see my mistake here. I suppose writing a quick fix at 3 in the morning doesn't produce the best code. I will fix, test, and update my PR.

**Comment by jacksonp52** [comment]
I have updated my PR, and I have done some testing to ensure landmines spawn in the level normally, as well as spawning (and exploding) upon the player's death.

**Comment by Chrigi2486** [comment]
Looks good, I'll accept the merge request and ask Tom to update the Thunderstore page!

**Comment by Toemmsen96** [comment]
The update should now be live!
Thanks a lot for the fix!
